languageCode = "ca"
languageName = "Català"
weight = 4
title = "L01D"

[params]
displayName = "Català"
isoCode = "ca"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "L01D"
image = "IMG_3225.jpeg"
headline = "Un solitari, un filòsof."
bio = "Un solitari, un filòsof."