languageCode = "la"
languageName = "Latina"
weight = 1
title = "L01D"

[params]
displayName = "Latina"
isoCode = "la"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "L01D"
image = "IMG_3225.jpeg"
headline = "anteriore excellentu alumnu, sed ego non lu esse iam"
bio = "anu solitariu, philosŏphu."
