languageCode = "en"
languageName = "English"
weight = 2
title = "Aristonous"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "Aristonous"
image = "IMG_3225.jpeg"
headline = "A weird person."
bio = "Self-proclaimed philosopher"
