languageCode = "en"
languageName = "English"
weight = 2
title = "L01D"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "L01D"
image = "IMG_3225.jpeg"
headline = "Formerly an excellent student, but now I'm not."
bio = "A loner, a philosopher."
