[[footer]]
name = "Tags"
pageRef = "tags"
weight = 1

[[footer]]
name = "Categorías"
pageRef = "categories"
weight = 2

[[footer]]
name = "Estado"
url = "https://l01d.openstatus.dev/"
identifier = "vxScehyusI"
weight = 3

[[footer]]
name = "Estadística"
url = "https://cloud.umami.is/share/hgTNxfNOtWvgfRKK/l01d.pages.dev"
identifier = "58kIewLIZI"
weight = 4

[[main]]
none = "none"

[[main]]
name = "Proyectos"
pageRef = "projects"
identifier = "5ZCkMTWhMu"
weight = 1

[[main]]
name = "Sobre"
pageRef = "about"
identifier = "BChxSd7hCX"
weight = 2