[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "categorĭas"
pageRef = "categories"
weight = 20

[[main]]
none = "none"

[[main]]
name = "projectus"
pageRef = "projects"
identifier = "5ZCkMTWhMu"
weight = 1