[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20

[[footer]]
name = "Status"
url = "https://l01d-status.openstatus.dev/"
identifier = "vxScehyusI"
weight = 9999

[[main]]
none = "none"

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "5ZCkMTWhMu"
weight = 1

[[main]]
name = "About"
pageRef = "about"
identifier = "BChxSd7hCX"
weight = 2
