[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20

[[main]]
none = "none"

[[main]]
name = "Projectes"
pageRef = "projects"
identifier = "5ZCkMTWhMu"
weight = 1