[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categorías"
pageRef = "categories"
weight = 20

[[main]]
none = "none"

[[main]]
name = "Proyectos"
pageRef = "projects"
identifier = "5ZCkMTWhMu"
weight = 1

[[main]]
name = "Sobre"
pageRef = "about"
identifier = "BChxSd7hCX"
weight = 2