[[footer]]
name = "tags"
pageRef = "tags"
weight = 1

[[footer]]
name = "categorĭas"
pageRef = "categories"
weight = 2

[[footer]]
name = "statu"
url = "https://l01d-status.openstatus.dev/"
identifier = "vxScehyusI"
weight = 3


[[main]]
none = "none"

[[main]]
name = "projectus"
pageRef = "projects"
identifier = "5ZCkMTWhMu"
weight = 1

[[main]]
name = "super"
pageRef = "about"
identifier = "BChxSd7hCX"
weight = 2